#!/usr/bin/ash

run_earlyhook() {
    if [ -e /etc/vt_color/default ]
    then
        setcolors -c /dev/console /etc/vt_color/default
    else
        msg "No consolecolors found despite added hook."
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
